### ISSUE TITLE
InvalidDimensionException when running on ECS Fargate with fluent-bit

### ISSUE THREAD

**Issue by markkuhn** [awslabs/aws-embedded-metrics-java#125]
An `InvalidDimensionException` is being thrown when using fluent-bit since `getLogGroupName()` is returning an empty string:

https://github.com/awslabs/aws-embedded-metrics-java/blob/19ef5ca3b888ab3469be7860d0d339fe682473f6/src/main/java/software/amazon/cloudwatchlogs/emf/environment/ECSEnvironment.java#L101-L107

**Comment by rohitnair** [comment]
Is there an ETA for the fix, or a workaround to avoid this issue?

**Comment by markkuhn** [comment]
@rohitnair 
A fix is being worked on. I do not have an ETA for you.

For now you can turn off default dimensions by calling `resetDimensions(false)` before you start setting your own custom dimensions. This will clear all dimensions and stop using [default dimensions](https://github.com/awslabs/aws-embedded-metrics-java/blob/19ef5ca3b888ab3469be7860d0d339fe682473f6/src/main/java/software/amazon/cloudwatchlogs/emf/logger/MetricsLogger.java#L268-L270).
More information on resetDimensions() [here](https://github.com/awslabs/aws-embedded-metrics-java#api).
