### ISSUE TITLE
ECS fargate is not working with EMF

### ISSUE THREAD

**Issue by vkatoch2000** [awslabs/aws-embedded-metrics-java#139]
**Problem:**
We have migrated to embedded metrics logger, suddenly it stops logging metrics to cloudwatch

**AWS Service:**
ECS fargate

**Log driver used in ECS container defintion**
We are using 
          LogConfiguration:
              LogDriver: awslogs

**Questions**:
Do we need to use separate LogDriver  or ECS cloudwatch agent (non-blocking)  as side car, any pointer ??
We want log metrics in blocking mode like awslogs driver

**Comment by gordonpn** [comment]
Are you seeing any logs appear into the log group that you specified in your logging configuration?

Using this EMF Java library, when you write the EMF logs to stdout, you should see them appear in the log group configured.

**Comment by vkatoch2000** [comment]
software.amazon.cloudwatchlogs.emf.MetricsBufferLogger.addMetric(extensionContext.getRequiredTestMethod().getName().concat(" - Failed")); this is not creating any metrics in cloudwatch

            log.info("Test Failed {}", extensionContext.getRequiredTestMethod().getName());
This is creating logs in cloudwatch using slf4j

**Comment by gordonpn** [comment]
1. Could you link me to `MetricsBufferLogger`?
2. You must call the `flush()` method in order to serialize and write the log to stdout.

**Comment by vkatoch2000** [comment]
public class CloudWatchMetricsBufferLogger extends CloudWatchMetricsLogger {
  private final MetricsLogger metricsLogger;
  private final String namespace;
  private DimensionSet dimension = new DimensionSet();
  private static final Logger log = LoggerFactory.getLogger(CloudWatchMetricsBufferLogger.class);
  private final Map<String, AtomicInteger> localMetrics = new ConcurrentHashMap();
  private final AtomicInteger metricCounter = new AtomicInteger(0);

  public CloudWatchMetricsBufferLogger(String namespace) {
    this.namespace = (String)Objects.requireNonNull(namespace);
    this.metricsLogger = new MetricsLogger();
  }

  public CloudWatchMetricsBufferLogger(String namespace, MetricsLogger metricsLogger) {
    this.namespace = (String)Objects.requireNonNull(namespace);
    this.metricsLogger = metricsLogger;
  }

  public void addCustomMetric(String name, double value, Unit unit) {
    try {
      this.metricCounter.getAndIncrement();
      this.metricsLogger.setNamespace(this.namespace);
      this.metricsLogger.putMetric(name, value, unit);
      if (this.dimension != null) {
        this.metricsLogger.setDimensions(new DimensionSet[]{this.dimension});
      }
    } catch (InvalidNamespaceException | InvalidMetricException var6) {
      log.error("Error occurred while setting up EMF metrics: ", var6);
    }

  }

  public void send() {
    if (this.metricCounter.get() > 0) {
      this.metricsLogger.flush();
      this.metricCounter.set(0);
    }

  }

  public void addDimension(String key, String value) {
    try {
      this.dimension.addDimension(key, value);
    } catch (InvalidDimensionException | DimensionSetExceededException var4) {
      log.error("Error occurred while adding dimension: ", var4);
    }

  }

  public void addMetricsWithoutCloudWatch(String metricsName, Integer value) {
    this.localMetrics.computeIfAbsent(metricsName, (v) -> {
      return new AtomicInteger(0);
    });
    ((AtomicInteger)this.localMetrics.get(metricsName)).getAndAdd(value);
  }

  public Map<String, AtomicInteger> getAndResetLocalMetrics() {
    Map<String, AtomicInteger> metrics = new HashMap(this.localMetrics);
    this.localMetrics.clear();
    return metrics;
  }
}

**Comment by vkatoch2000** [comment]
> 1. Could you link me to `MetricsBufferLogger`?
> 2. You must call the `flush()` method in order to serialize and write the log to stdout.
we are calling it

sorry its MetricsLogger not **MetricsBufferLogger**

**Comment by vkatoch2000** [comment]
@gordonpn is this à issue or i am doing something wrong ??

**Comment by gordonpn** [comment]
It looks like the issue is related to your implementation and not an issue with the library.

The library is in a stable state.

**Comment by vkatoch2000** [comment]
Have you found any gaps in code above ?

**Comment by vkatoch2000** [comment]
it has been fixed using ECS cloudwatch agent as side car container
