### ISSUE TITLE
Added support for more than 100 metrics

### ISSUE THREAD

**Issue by yaozhaoy** [awslabs/aws-embedded-metrics-java#41]
The EMF spec limits the max number of metrics in one log event to 100. The java library needs to follow the spec

> Metrics— An array of MetricDefinition objects. This array MUST NOT contain more than 100 MetricDefinition objects.

**Comment by janimationd** [comment]
Hi, now that this is resolved, can you please update the Readme.md with the new limit information? https://github.com/awslabs/aws-embedded-metrics-java/blob/master/README.md?plain=1#L80
