### ISSUE TITLE
Support explicitly specifying the environment

### ISSUE THREAD

**Issue by rogeitan** [awslabs/aws-embedded-metrics-java#43]
We want to be able to explicitly set the environment, both as part of testing and because working with environment variables is messy.

However, the only way to do that right now is to copy/paste the environment source code to a new class and subclass EnvironmentProvider to override resolveEnvironment(), since all of them are package-private and EnvironmentProvider doesn't let you specify.

Is there a particular reason these are locked down?  If not, we'd greatly appreciate it if you could make the environments public so we can reuse them and/or instantiate EnvironmentProvider pointing to a specific one.

**Comment by yaozhaoy** [comment]
You can use the Configuration to override the environment. 

See [code](https://github.com/awslabs/aws-embedded-metrics-java/blob/master/src/main/java/software/amazon/cloudwatchlogs/emf/config/Configuration.java#L55)
