### ISSUE TITLE
Question of usage of default dimensions

### ISSUE THREAD

**Issue by romanfq** [awslabs/aws-embedded-metrics-java#55]
I want to be able to issue embedded metrics inside a Lambda without the default dimensions that get automatically added to the metrics context [upon flush](https://github.com/awslabs/aws-embedded-metrics-java/pull/3/commits/b437afedab4627b3fbb66be0f1c40d81ab34eab8#diff-f5ecd100d93e5ef77bb23441c749ff2cdbc3e1b501b22a3eefd4171bc161f820R108-R115) by `configureContextForEnvironment`.

I used a hint in the documentation to use `setDimensions` in the `MetricsLogger` instance, to no avail. Setting an empty `DimensionSet` this way has no effect- which could be an accidental bug.

Is there a workaround planned for this?

**Comment by yaozhaoy** [comment]
Verify that if you call setDimensions() without any parameter, the serialized log events would not contain the default dimensions.
