### ISSUE TITLE
Give users the flexibility of using/not using default dimensions

### ISSUE THREAD

**Issue by soumyaumass** [awslabs/aws-embedded-metrics-java#57]

**Comment by jaredcnance** [comment]
Does setDimensions not work for you?

https://github.com/awslabs/aws-embedded-metrics-java/blob/5089893d1c8157bde9f4f62022b91ee0b18e1a34/src/main/java/software/amazon/cloudwatchlogs/emf/logger/MetricsLogger.java#L99-L111

**Comment by jaredcnance** [comment]
Possibly related to #55

**Comment by romanfq** [comment]
I don't think the suggestion to use `setDimensions` work because of this code in MetricsLogger:

```
private void configureContextForEnvironment(MetricsContext context, Environment environment) {
        if (context.hasDefaultDimensions())
            return;
        DimensionSet defaultDimension = new DimensionSet();
        defaultDimension.addDimension("LogGroup", environment.getLogGroupName());
        defaultDimension.addDimension("ServiceName", environment.getName());
        defaultDimension.addDimension("ServiceType", environment.getType());
        context.setDefaultDimensions(defaultDimension);
    }
```

Assume you can, and then you will see that the first line there returns `false`, and a new set of default dimensions is added in subsequent lines.

**Comment by liangjacky** [comment]
Yes. Having the options to not have the default dimensions would be nice. Referring to `LogGroup` `ServiceName` and `ServiceType`

**Comment by jaredcnance** [comment]
This is a bug then. The intention behind setDimensions is to set and override all dimensions on the current logger.

**Comment by yaozhaoy** [comment]
When you call the [setDimension](https://github.com/awslabs/aws-embedded-metrics-java/blob/master/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricDirective.java#L88), it would set a flag to disable the defaultDimension. Do you have a code snippet to reproduce the bug?

**Comment by IvanMwiruki** [comment]
As @romanfq alluded, `configureContextForEnvironment` doesn't seem to care about any flags. 

```
    @Test
    public void defaultDimensionsStillSet() {
        MetricsContext context = new MetricsContext();
        MetricsLogger logger = new MetricsLogger(new EnvironmentProvider(), context);
        logger.setDimensions(DimensionSet.of("foo", "bar"));
        logger.flush();

        System.out.println(context.getDefaultDimensions().getDimensionKeys()); // default dimensions
        context.getDimensions().stream().map(DimensionSet::getDimensionKeys).forEach(System.out::println); // all dimensions
    }
```

Prints
```
[LogGroup, ServiceName, ServiceType]
[foo]
```

I would expect
```
[]
[foo]
```

Also looks like the doc for `context.getDimensions()` aren't accurate. Says ` /** @return the list of dimensions that has been added, including default dimensions. */` but the returned list doesn't include default dimensions.

**Comment by yaozhaoy** [comment]
When call the setDimension(), there's flag `shouldUseDefaultDimension` set to false and the default dimensions would be ignored in serialization, though the default dimensions is still in the context object.
