### ISSUE TITLE
Is it LogGroup or LogGroupName

### ISSUE THREAD

**Issue by henrik-larsson-15-wcar** [awslabs/aws-embedded-metrics-java#58]
When checking the output of this lib I get the following:
```
{"_aws":{"Timestamp":1604580388149,"CloudWatchMetrics":[{"Namespace":"my/metrics","Metrics":[{"Name":"ProcessingLatency","Unit":"Milliseconds"}],"Dimensions":[["LogGroup","ServiceName","ServiceType","mytestintegration"]]}]},"RequestId":"422b1569-16f6-4a03-b8f0-fe3fd9b100f8","ProcessingLatency":100.0,"LogGroup":"Unknown-metrics","ServiceName":"Unknown","ServiceType":"Unknown","mytestintegration":"Aggregator"}
```

However when checking the official documentation [official documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_CloudWatch_Agent.html) is states that it should be LogGroupName like this in the example

```
echo '{"_aws":{"Timestamp":1574109732004,"LogGroupName":"Foo","CloudWatchMetrics":[{"Namespace":"MyApp","Dimensions":[["Operation"]],"Metrics":[{"Name":"ProcessingLatency","Unit":"Milliseconds"}]}]},"Operation":"Aggregator","ProcessingLatency":100}' \
> /dev/udp/0.0.0.0/25888
```

And when I check the [EMF specification](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) it does not even mention LogGroupName.

Very confusing and not sure what is correct.

**Comment by jaredcnance** [comment]
The LogGroupName is specific to the CloudWatch Agent as an instruction on where to direct the log events. It is not a requirement of EMF which is why it is not part of the data specification. Other agents such as FluentBit use a configuration file to define the log group name. The LogGroup dimension is a default dimension to allow linking between the logs and metrics.

**Comment by henrik-larsson-15-wcar** [comment]
Aa thanks for explaining.
