### ISSUE TITLE
[Bug] calling MetricsLogger setDimensions() followed by putDimensions() throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by neukev** [awslabs/aws-embedded-metrics-java#59]
Calling [setDimensions() in MetricsLogger](https://github.com/awslabs/aws-embedded-metrics-java/blob/master/src/main/java/software/amazon/cloudwatchlogs/emf/logger/MetricsLogger.java#L109) forwards to MetricsContext which [calls Arrays.asList()](https://github.com/awslabs/aws-embedded-metrics-java/blob/5089893d1c8157bde9f4f62022b91ee0b18e1a34/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricsContext.java#L179). This returns a fixed-size list that does not support add() ([JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#asList-T...-)). Therefore, the following code throws a `java.lang.UnsupportedOperationException`.  

```
MetricsLogger logger = new MetricsLogger();
logger.setDimensions(DimensionSet.of("foo", "bar"));
logger.putDimensions(DimensionSet.of("foobar", "baz"));
```

**Comment by IvanMwiruki** [comment]
https://github.com/awslabs/aws-embedded-metrics-java/pull/62
