### ISSUE TITLE
Repeated Construction of ObjectMapper hurting performance

### ISSUE THREAD

**Issue by jonnekaunisto** [awslabs/aws-embedded-metrics-java#66]
I have an application that is publishing a lot of metrics.

Through profiling I was able to see that around 3% of CPU usage was going into repeatedly constructing ObjectMapper in the EMF library.

I narrowed it down to this constructor: https://github.com/awslabs/aws-embedded-metrics-java/blob/4ccacf6836f8b81730ee19f4268befc1de37d438/src/main/java/software/amazon/cloudwatchlogs/emf/model/RootNode.java#L49

Is it possible to make the ObjectMapper static?

**Comment by jaredcnance** [comment]
Closed by #67
