### ISSUE TITLE
Metric Value List can go above MetricDefinition limits, causing CW missing metrics

### ISSUE THREAD

**Issue by axeliux** [awslabs/aws-embedded-metrics-java#72]
Apparently if you call ```MetricsLogger.putMetric()``` more than 100 times, it will keep adding values to the metric causing to reach out of it's limits.  This would cause missing metrics as the log entry would not be processed.

Reference:

Metrics— An array of MetricDefinition objects. This array MUST NOT contain more than 100 MetricDefinition objects.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html

**Comment by axeliux** [comment]
Maybe we are not limiting the size of the metric value at all.

https://github.com/awslabs/aws-embedded-metrics-java/blob/b6a99c020e04ebd9942bbf6778d520746beb87f3/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricDirective.java#L64

**Comment by msailes** [comment]
It's not just the number of metrics, it's all validation.

Size of numbers, infinity...

**Comment by axeliux** [comment]
I wonder if instead of having a ```new ArrayList<>``` to store the metric values, we could have something like ```EvictingQueue`` of a fixed size 100.

I understand that we could lose some metrics values,  but given the current 100 limitation, it would be better than not having a metric at all.

https://github.com/awslabs/aws-embedded-metrics-java/blob/b6a99c020e04ebd9942bbf6778d520746beb87f3/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricDefinition.java#L49

https://guava.dev/releases/snapshot/api/docs/com/google/common/collect/EvictingQueue.html

**Comment by axeliux** [comment]
Looks like somebody have already work around this issue:

https://github.com/awslabs/aws-embedded-metrics-java/pull/42/files/dc47697d0a860c46dbbc06669558452ffa28e117
