### ISSUE TITLE
[Question] Is it possible to set logGroup retention time other then ```Never expire``` ? 

### ISSUE THREAD

**Issue by miguelcss** [awslabs/aws-embedded-metrics-java#90]
Hello,

By default the lib creates a logGroup with retention set to ```Never expire```. Is it possible to override this behavior with configuration? I could not find it.

Thank you

**Comment by miguelcss** [comment]
Any feedback on this?

**Comment by arielapostoli** [comment]
@miguelcss  this is currently not possible. Part of the reason for not supporting custom retention is that it could lead to discrepancies and ambiguity, should retention durations differ between different publishing instances. A work around is to set retention through CloudWatch Logs CLI or API calls after loggroup creation, or creating the loggroup prior to emitting EMF logs.

**Comment by miguelcss** [comment]
@arielapostoli , thank you for you clarification, I've created and set directly on cloudwatch group as you suggested.
