### ISSUE TITLE
Need to specify the CloudWatch region to use

### ISSUE THREAD

**Issue by xxn5788** [awslabs/aws-embedded-metrics-java#96]
We're having a requirement to collect metrics from Lambda and send those to multiple specific CloudWatch region.

When we're searching for solution for ECS, we found CloudWatch Agent has a region field provided:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html

region – Specifies the Region to use for the CloudWatch endpoint when an Amazon EC2 instance is being monitored. The metrics collected are sent to this Region, such as us-west-1. If you omit this field, the agent sends metrics to the Region where the Amazon EC2 instance is located.

We hope to have a similar field available for AWS EMF library so we can specify the CloudWatch region we're going to use.

**Comment by jaredcnance** [comment]
This is not possible today. With EMF, the destination is always dependent on the process actually sending the events to CloudWatch. I'm guessing you're publishing events on Lambda (if not there may be other options for you depending on your compute environment). In the case of Lambda, we would need Lambda to support cross-region log publication which they don't do today.

**Comment by xxn5788** [comment]
Thanks!
